# Generated by Django 4.2.2 on 2023-06-26 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('year_of_birth', models.IntegerField()),
                ('country', models.CharField(max_length=50)),
                ('biography', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ('last_name', 'first_name', 'year_of_birth'),
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('address_1', models.CharField(max_length=50)),
                ('house_number', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='PublicationAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookApp.author')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookApp.publication')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('isbn', models.CharField(max_length=17)),
                ('content', models.TextField(blank=True, null=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='cover_images/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookApp.author')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookApp.publication')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
